#!/bin/sh

cp ~/.ssh/config ~/.ssh/config.bak

START='# BEGIN GIT'
END='# END GIT'

if ! grep -q "$START" ~/.ssh/config; then
  echo "Make sure you have the '# BEGIN GIT' and '# END GIT' comments in '~/.ssh/config'."
  exit 1
fi

PROFILE_1_USER='user1'
PROFILE_1_EMAIL='user1@example.com'
PROFILE_1_SSH_CONFIG='Host github.com
  HostName github.com
  User git
  IdentityFile ~/.ssh/id_rsa'

PROFILE_2_USER='user2'
PROFILE_2_EMAIL='user2@example.com'
PROFILE_2_SSH_CONFIG='Host github.com
  HostName github.com
  User git
  IdentityFile ~/.ssh/alt_github_ssh_key.pem'

switchup() {
  git config --global user.name "$GIT_USER"
  git config --global user.email "$GIT_EMAIL"
  tmp1="$(mktemp)"
  tmp2="$(mktemp)"
  echo "$GIT_SSH_CONFIG" > "$tmp1"
  sed -e "/$START/,/$END/{ /$START/{p; r $tmp1
        }; /$END/p; d }" ~/.ssh/config > $tmp2
  mv "$tmp2" ~/.ssh/config
  rm -f "$tmp1"
}

if git config --global user.name | grep -q "$PROFILE_1_USER"; then
  GIT_USER="$PROFILE_2_USER"
  GIT_EMAIL="$PROFILE_2_EMAIL"
  GIT_SSH_CONFIG="$PROFILE_2_SSH_CONFIG"
else
  GIT_USER="$PROFILE_1_USER"
  GIT_EMAIL="$PROFILE_1_EMAIL"
  GIT_SSH_CONFIG="$PROFILE_1_SSH_CONFIG"
fi

switchup

echo "current git user: $(git config --global user.name)"
